<?php

namespace Modules\Accounts\Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LedgerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {      
        DB::table('ledgers')->insert(array (
         0 => array(
            'name' => 'Assets',
            'code' => 'A1001',
            'type' => 1,
            'parent_id' => 0,
            'level' => 1,
            'is_active' => 1,
            'acc_type' => 'others',
            'view_in_bs' => 0,
            'view_in_is' => 0,
         ),
         1 => array(
            'name' => 'Non-Current Assets',
            'code' => 'A1002',
            'type' => 1,
            'parent_id' => 1,
            'level' => 2,
            'is_active' => 1,
            'acc_type' => 'others',
            'view_in_bs' => 1,
            'view_in_is' => 0,
         ),
         2 => array(
            'name' => 'Current Asset',
            'code' => 'A1003',
            'type' => 1,
            'parent_id' => 1,
            'level' => 2,
            'is_active' => 1,
            'acc_type' => 'others',
            'view_in_bs' => 1,
            'view_in_is' => 0,
         ),
         3 => array(
            'name' => 'Bank Balance',
            'code' => 'A1004',
            'type' => 1,
            'parent_id' => 3,
            'level' => 3,
            'is_active' => 1,
            'acc_type' => 'bank',
            'view_in_bs' => 1,
            'view_in_is' => 0,
         ),
         4 => array(
            'name' => 'Cash Balance',
            'code' => 'A1005',
            'type' => 1,
            'parent_id' => 3,
            'level' => 3,
            'is_active' => 1,
            'acc_type' => 'cash',
            'view_in_bs' => 1,
            'view_in_is' => 0,
         ),
         5 => array(
            'name' => 'Accounts Receivable AC',
            'code' => 'A1006',
            'type' => 1,
            'parent_id' => 3,
            'level' => 3,
            'is_active' => 1,
            'acc_type' => 'others',
            'view_in_bs' => 1,
            'view_in_is' => 0,
         ),
         6 => array(
            'name' => 'Inventory',
            'code' => 'A1007',
            'type' => 1,
            'parent_id' => 3,
            'level' => 3,
            'is_active' => 1,
            'acc_type' => 'others',
            'view_in_bs' => 1,
            'view_in_is' => 0,
         ),
         7 => array(
            'name' => 'Inter-Company Current Account',
            'code' => 'A1008',
            'type' => 1,
            'parent_id' => 3,
            'level' => 3,
            'is_active' => 1,
            'acc_type' => 'others',
            'view_in_bs' => 1,
            'view_in_is' => 0,
         ),
         8 => array(
            'name' => 'Liabilities',
            'code' => 'L2001',
            'type' => 2,
            'parent_id' => 0,
            'level' => 1,
            'is_active' => 1,
            'acc_type' => 'others',
            'view_in_bs' => 0,
            'view_in_is' => 0,
         ),
         9 => array(
            'name' => 'Authorized Capital',
            'code' => 'E5004',
            'type' => 5,
            'parent_id' => 30,
            'level' => 2,
            'is_active' => 1,
            'acc_type' => 'others',
            'view_in_bs' => 1,
            'view_in_is' => 0,
         ),
         10 => array(
            'name' => 'Capital Account',
            'code' => 'L2002',
            'type' => 2,
            'parent_id' => 10,
            'level' => 2,
            'is_active' => 1,
            'acc_type' => 'others',
            'view_in_bs' => 1,
            'view_in_is' => 0,
         ),
         11 => array(
            'name' => 'Current Liabilities',
            'code' => 'L2003',
            'type' => 2,
            'parent_id' => 9,
            'level' => 2,
            'is_active' => 1,
            'acc_type' => 'others',
            'view_in_bs' => 1,
            'view_in_is' => 0,
         ),
         12 => array(
            'name' => 'Company Tax Liabilities',
            'code' => 'L2004',
            'type' => 2,
            'parent_id' => 12,
            'level' => 2,
            'is_active' => 1,
            'acc_type' => 'others',
            'view_in_bs' => 1,
            'view_in_is' => 0,
         ),
         13 => array(
            'name' => 'Tax Payable',
            'code' => 'L2005',
            'type' => 2,
            'parent_id' => 13,
            'level' => 3,
            'is_active' => 1,
            'acc_type' => 'others',
            'view_in_bs' => 1,
            'view_in_is' => 0,
         ),
         14 => array(
            'name' => 'Accounts Payable AC',
            'code' => 'L2006',
            'type' => 2,
            'parent_id' => 12,
            'level' => 3,
            'is_active' => 1,
            'acc_type' => 'others',
            'view_in_bs' => 1,
            'view_in_is' => 0,
         ),
         15 => array(
            'name' => 'Expenses',
            'code' => 'E3001',
            'type' => 3,
            'parent_id' => 0,
            'level' => 1,
            'is_active' => 1,
            'acc_type' => 'others',
            'view_in_bs' => 0,
            'view_in_is' => 0,
         ),
         16 => array(
            'name' => 'Cost of Sales & Services',
            'code' => 'E3002',
            'type' => 3,
            'parent_id' => 16,
            'level' => 2,
            'is_active' => 1,
            'acc_type' => 'others',
            'view_in_bs' => 0,
            'view_in_is' => 0,
         ),
         17 => array(
            'name' => 'Others Cost Expenses',
            'code' => 'E3003',
            'type' => 3,
            'parent_id' => 16,
            'level' => 2,
            'is_active' => 1,
            'acc_type' => 'others',
            'view_in_bs' => 0,
            'view_in_is' => 0,
         ),
         18 => array(
            'name' => 'Administrative & Operation Expenses',
            'code' => 'E3004',
            'type' => 3,
            'parent_id' => 16,
            'level' => 2,
            'is_active' => 1,
            'acc_type' => 'others',
            'view_in_bs' => 0,
            'view_in_is' => 0,
         ),
         19 => array(
            'name' => 'TAX Expenses',
            'code' => 'E3005',
            'type' => 3,
            'parent_id' => 16,
            'level' => 2,
            'is_active' => 1,
            'acc_type' => 'others',
            'view_in_bs' => 0,
            'view_in_is' => 0,
         ),
         20 => array(
            'name' => 'Company Income TAX',
            'code' => 'E3006',
            'type' => 3,
            'parent_id' => 20,
            'level' => 3,
            'is_active' => 1,
            'acc_type' => 'others',
            'view_in_bs' => 0,
            'view_in_is' => 0,
         ),
         21 => array(
            'name' => 'Purchase AC',
            'code' => 'E3007',
            'type' => 3,
            'parent_id' => 17,
            'level' => 3,
            'is_active' => 1,
            'acc_type' => 'others',
            'view_in_bs' => 0,
            'view_in_is' => 0,
         ),
         22 => array(
            'name' => 'Salary Expenses',
            'code' => 'E3008',
            'type' => 3,
            'parent_id' => 19,
            'level' => 3,
            'is_active' => 1,
            'acc_type' => 'others',
            'view_in_bs' => 0,
            'view_in_is' => 0,
         ),
         23 => array(
            'name' => 'Revenue',
            'code' => 'I4001',
            'type' => 4,
            'parent_id' => 0,
            'level' => 1,
            'is_active' => 1,
            'acc_type' => 'others',
            'view_in_bs' => 0,
            'view_in_is' => 0,
         ),
         24 => array(
            'name' => 'Discount on Sales',
            'code' => 'I4002',
            'type' => 4,
            'parent_id' => 24,
            'level' => 2,
            'is_active' => 1,
            'acc_type' => 'others',
            'view_in_bs' => 0,
            'view_in_is' => 0,
         ),
         25 => array(
            'name' => 'Non-Operating Income',
            'code' => 'I4003',
            'type' => 4,
            'parent_id' => 24,
            'level' => 2,
            'is_active' => 1,
            'acc_type' => 'others',
            'view_in_bs' => 0,
            'view_in_is' => 1,
         ),
         26 => array(
            'name' => 'Sales Revenue',
            'code' => 'I4004',
            'type' => 4,
            'parent_id' => 24,
            'level' => 2,
            'is_active' => 1,
            'acc_type' => 'others',
            'view_in_bs' => 0,
            'view_in_is' => 1,
         ),
         27 => array(
            'name' => 'Financial Expenses',
            'code' => 'E3009',
            'type' => 3,
            'parent_id' => 16,
            'level' => 2,
            'is_active' => 1,
            'acc_type' => 'others',
            'view_in_bs' => 0,
            'view_in_is' => 0,
         ),
         28 => array(
            'name' => 'Sales From Water Engineering Projects',
            'code' => 'I4005',
            'type' => 4,
            'parent_id' => 24,
            'level' => 2,
            'is_active' => 1,
            'acc_type' => 'others',
            'view_in_bs' => 0,
            'view_in_is' => 0,
         ),
         29 => array(
            'name' => 'Equities',
            'code' => 'E5001',
            'type' => 5,
            'parent_id' => 0,
            'level' => 1,
            'is_active' => 1,
            'acc_type' => 'others',
            'view_in_bs' => 0,
            'view_in_is' => 0,
         ),
         30 => array(
            'name' => 'Shareholder\'s Equity',
            'code' => 'E5002',
            'type' => 5,
            'parent_id' => 30,
            'level' => 1,
            'is_active' => 1,
            'acc_type' => 'others',
            'view_in_bs' => 1,
            'view_in_is' => 0,
         ),
         31 => array(
            'name' => 'Share Capital',
            'code' => 'E5003',
            'type' => 5,
            'parent_id' => 31,
            'level' => 1,
            'is_active' => 1,
            'acc_type' => 'others',
            'view_in_bs' => 1,
            'view_in_is' => 0,
         ),
         32 => array(
            'name' => 'Conveyance Bill',
            'code' => 'E3010',
            'type' => 3,
            'parent_id' => 19,
            'level' => 3,
            'is_active' => 1,
            'acc_type' => 'others',
            'view_in_bs' => 0,
            'view_in_is' => 0,
         ),
         33 => array(
            'name' => 'Printing and Stationary',
            'code' => 'E3011',
            'type' => 3,
            'parent_id' => 19,
            'level' => 3,
            'is_active' => 1,
            'acc_type' => 'others',
            'view_in_bs' => 0,
            'view_in_is' => 0,
         ),
         34 => array(
            'name' => 'Allowance',
            'code' => 'E3012',
            'type' => 3,
            'parent_id' => 19,
            'level' => 3,
            'is_active' => 1,
            'acc_type' => 'others',
            'view_in_bs' => 0,
            'view_in_is' => 0,
         ),
         35 => array(
            'name' => 'Office Rent',
            'code' => 'E3013',
            'type' => 3,
            'parent_id' => 19,
            'level' => 3,
            'is_active' => 1,
            'acc_type' => 'others',
            'view_in_bs' => 0,
            'view_in_is' => 1,
         ),
         36 => array(
            'name' => 'VAT on Office Rent Payable',
            'code' => 'L2057',
            'type' => 3,
            'parent_id' => 12,
            'level' => 3,
            'is_active' => 1,
            'acc_type' => 'others',
            'view_in_bs' => 0,
            'view_in_is' => 0,
         ),
         37 => array(
            'name' => 'Entertainment bill',
            'code' => 'E3014',
            'type' => 3,
            'parent_id' => 19,
            'level' => 3,
            'is_active' => 1,
            'acc_type' => 'others',
            'view_in_bs' => 0,
            'view_in_is' => 0,
         ),
         38 => array(
            'name' => 'Medical and Treatment',
            'code' => 'E3015',
            'type' => 3,
            'parent_id' => 19,
            'level' => 3,
            'is_active' => 1,
            'acc_type' => 'others',
            'view_in_bs' => 0,
            'view_in_is' => 0,
         ),
         39 => array(
            'name' => 'Electricity Bill',
            'code' => 'E3016',
            'type' => 3,
            'parent_id' => 19,
            'level' => 3,
            'is_active' => 1,
            'acc_type' => 'others',
            'view_in_bs' => 0,
            'view_in_is' => 0,
         ),
         40 => array(
            'name' => 'Wasa Bill',
            'code' => 'E3017',
            'type' => 3,
            'parent_id' => 19,
            'level' => 3,
            'is_active' => 1,
            'acc_type' => 'others',
            'view_in_bs' => 0,
            'view_in_is' => 0,
         ),
         41 => array(
            'name' => 'Electrical and Computer Accessories',
            'code' => 'E3018',
            'type' => 3,
            'parent_id' => 19,
            'level' => 3,
            'is_active' => 1,
            'acc_type' => 'others',
            'view_in_bs' => 0,
            'view_in_is' => 0,
         ),
         42 => array(
            'name' => 'Office Maintenance',
            'code' => 'E3019',
            'type' => 3,
            'parent_id' => 19,
            'level' => 3,
            'is_active' => 1,
            'acc_type' => 'others',
            'view_in_bs' => 0,
            'view_in_is' => 0,
         ),
         43 => array(
            'name' => 'Repair and Maintenance',
            'code' => 'E3020',
            'type' => 3,
            'parent_id' => 19,
            'level' => 3,
            'is_active' => 1,
            'acc_type' => 'others',
            'view_in_bs' => 0,
            'view_in_is' => 0,
         ),
         44 => array(
            'name' => 'Car & Vehicles Maintenace',
            'code' => 'E3021',
            'type' => 3,
            'parent_id' => 19,
            'level' => 3,
            'is_active' => 1,
            'acc_type' => 'others',
            'view_in_bs' => 0,
            'view_in_is' => 0,
         ),
         45 => array(
            'name' => 'Postage & Courier',
            'code' => 'E3022',
            'type' => 3,
            'parent_id' => 19,
            'level' => 3,
            'is_active' => 1,
            'acc_type' => 'others',
            'view_in_bs' => 0,
            'view_in_is' => 0,
         ),
         46 => array(
            'name' => 'Telephone & Mobile Bill',
            'code' => 'E3023',
            'type' => 3,
            'parent_id' => 19,
            'level' => 3,
            'is_active' => 1,
            'acc_type' => 'others',
            'view_in_bs' => 0,
            'view_in_is' => 0,
         ),
         47 => array(
            'name' => 'Tours & Travel Expense',
            'code' => 'E3024',
            'type' => 3,
            'parent_id' => 19,
            'level' => 3,
            'is_active' => 1,
            'acc_type' => 'others',
            'view_in_bs' => 0,
            'view_in_is' => 0,
         ),
         48 => array(
            'name' => 'Internet Bill',
            'code' => 'E3025',
            'type' => 3,
            'parent_id' => 19,
            'level' => 3,
            'is_active' => 1,
            'acc_type' => 'others',
            'view_in_bs' => 0,
            'view_in_is' => 0,
         ),
         49 => array(
            'name' => 'Audit Fee',
            'code' => 'E3026',
            'type' => 3,
            'parent_id' => 19,
            'level' => 3,
            'is_active' => 1,
            'acc_type' => 'others',
            'view_in_bs' => 0,
            'view_in_is' => 0,
         ),
         50 => array(
            'name' => 'Business Promotion Expenses',
            'code' => 'E3027',
            'type' => 3,
            'parent_id' => 19,
            'level' => 3,
            'is_active' => 1,
            'acc_type' => 'others',
            'view_in_bs' => 0,
            'view_in_is' => 0,
         ),
         51 => array(
            'name' => 'Purchase Discount',
            'code' => 'E3028',
            'type' => 3,
            'parent_id' => 17,
            'level' => 3,
            'is_active' => 1,
            'acc_type' => 'others',
            'view_in_bs' => 0,
            'view_in_is' => 0,
         ),
      ));
    }
}
